# pyuic5 -x pursuit2.ui -o ui_pursuit2.py

# -*- coding: utf-8 -*-

# fenetre principale de l'interface graphique


from PyQt5 import QtCore, QtGui, QtWidgets

from joueur import Joueur
from connect_bdd import Bdd
# from traitement_reponse import *
import random
import mysql.connector
import sys
import time
from traitement_reponse import traitement_reponse
from traitement_reponse import fonction_camembert	#peut-être pas nécéssaire
from traitement_reponse import question_finale	#idem
from fonction_question_aléatoire import question_aleatoire

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(660, 660)
        MainWindow.setMinimumSize(QtCore.QSize(660, 660))
        MainWindow.setMaximumSize(QtCore.QSize(660, 665))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 106, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 56, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 106, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 56, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 106, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 56, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 141, 151))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.groupBox.setPalette(palette)
        self.groupBox.setObjectName("groupBox")
        self.nom_1 = QtWidgets.QLabel(self.groupBox)
        self.nom_1.setGeometry(QtCore.QRect(16, 20, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.nom_1.setFont(font)
        self.nom_1.setAlignment(QtCore.Qt.AlignCenter)
        self.nom_1.setObjectName("nom_1")
        self.img1 = QtWidgets.QLabel(self.groupBox)
        self.img1.setGeometry(QtCore.QRect(36, 42, 71, 71))
        self.img1.setText("")
        self.img1.setPixmap(QtGui.QPixmap("images/Cam1.png"))
        self.img1.setScaledContents(True)
        self.img1.setAlignment(QtCore.Qt.AlignCenter)
        self.img1.setObjectName("img1")
        self.cam_1_1 = QtWidgets.QLabel(self.groupBox)
        self.cam_1_1.setEnabled(False)
        self.cam_1_1.setGeometry(QtCore.QRect(20, 120, 21, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.cam_1_1.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wingdings 2")
        font.setPointSize(14)
        self.cam_1_1.setFont(font)
        self.cam_1_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cam_1_1.setObjectName("cam_1_1")
        self.cam_2_1 = QtWidgets.QLabel(self.groupBox)
        self.cam_2_1.setEnabled(False)
        self.cam_2_1.setGeometry(QtCore.QRect(40, 120, 21, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.cam_2_1.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wingdings 2")
        font.setPointSize(14)
        self.cam_2_1.setFont(font)
        self.cam_2_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cam_2_1.setObjectName("cam_2_1")
        self.cam_3_1 = QtWidgets.QLabel(self.groupBox)
        self.cam_3_1.setEnabled(False)
        self.cam_3_1.setGeometry(QtCore.QRect(60, 120, 21, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.cam_3_1.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wingdings 2")
        font.setPointSize(14)
        self.cam_3_1.setFont(font)
        self.cam_3_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cam_3_1.setObjectName("cam_3_1")
        self.cam_4_1 = QtWidgets.QLabel(self.groupBox)
        self.cam_4_1.setEnabled(False)
        self.cam_4_1.setGeometry(QtCore.QRect(80, 120, 21, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.cam_4_1.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wingdings 2")
        font.setPointSize(14)
        self.cam_4_1.setFont(font)
        self.cam_4_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cam_4_1.setObjectName("cam_4_1")
        self.cam_5_1 = QtWidgets.QLabel(self.groupBox)
        self.cam_5_1.setEnabled(False)
        self.cam_5_1.setGeometry(QtCore.QRect(100, 120, 21, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(68, 221, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 221, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.cam_5_1.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wingdings 2")
        font.setPointSize(14)
        self.cam_5_1.setFont(font)
        self.cam_5_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cam_5_1.setObjectName("cam_5_1")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 260, 621, 361))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.frame.setPalette(palette)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lib_diffic = QtWidgets.QLabel(self.frame)
        self.lib_diffic.setGeometry(QtCore.QRect(246, 10, 121, 20))
        self.lib_diffic.setAlignment(QtCore.Qt.AlignCenter)
        self.lib_diffic.setObjectName("lib_diffic")
        self.champ = QtWidgets.QLineEdit(self.frame)
        self.champ.setGeometry(QtCore.QRect(190, 180, 241, 21))
        self.champ.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.champ.setText("")
        self.champ.setObjectName("champ")
        self.lib_vraifaux = QtWidgets.QLabel(self.frame)
        self.lib_vraifaux.setEnabled(True)
        self.lib_vraifaux.setGeometry(QtCore.QRect(270, 220, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lib_vraifaux.setFont(font)
        self.lib_vraifaux.setAlignment(QtCore.Qt.AlignCenter)
        self.lib_vraifaux.setObjectName("lib_vraifaux")
        self.label_35 = QtWidgets.QLabel(self.frame)
        self.label_35.setGeometry(QtCore.QRect(270, 140, 81, 20))
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.bok = QtWidgets.QPushButton(self.frame)
        self.bok.setGeometry(QtCore.QRect(450, 180, 31, 23))
        self.bok.setObjectName("bok")
        self.bsuite = QtWidgets.QPushButton(self.frame)
        self.bsuite.setEnabled(True)
        self.bsuite.setGeometry(QtCore.QRect(270, 330, 81, 23))
        self.bsuite.setObjectName("bsuite")
        self.lib_question = QtWidgets.QTextBrowser(self.frame)
        self.lib_question.setGeometry(QtCore.QRect(35, 40, 551, 91))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        self.lib_question.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.lib_question.setFont(font)
        self.lib_question.setObjectName("lib_question")
        self.lib_reponse = QtWidgets.QTextBrowser(self.frame)
        self.lib_reponse.setGeometry(QtCore.QRect(30, 250, 561, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lib_reponse.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.lib_reponse.setFont(font)
        self.lib_reponse.setObjectName("lib_reponse")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(330, 620, 321, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_33.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Kunstler Script")
        font.setPointSize(16)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.Titre = QtWidgets.QLabel(self.centralwidget)
        self.Titre.setGeometry(QtCore.QRect(36, 170, 571, 91))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.Titre.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Kunstler Script")
        font.setPointSize(72)
        self.Titre.setFont(font)
        self.Titre.setAlignment(QtCore.Qt.AlignCenter)
        self.Titre.setObjectName("Titre")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setGeometry(QtCore.QRect(340, 10, 141, 151))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.groupBox_3.setPalette(palette)
        self.groupBox_3.setObjectName("groupBox_3")
        self.nom_3 = QtWidgets.QLabel(self.groupBox_3)
        self.nom_3.setEnabled(True)
        self.nom_3.setGeometry(QtCore.QRect(16, 20, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.nom_3.setFont(font)
        self.nom_3.setAlignment(QtCore.Qt.AlignCenter)
        self.nom_3.setObjectName("nom_3")
        self.img3 = QtWidgets.QLabel(self.groupBox_3)
        self.img3.setGeometry(QtCore.QRect(36, 42, 71, 71))
        self.img3.setText("")
        self.img3.setPixmap(QtGui.QPixmap("images/Cam3.png"))
        self.img3.setScaledContents(True)
        self.img3.setAlignment(QtCore.Qt.AlignCenter)
        self.img3.setObjectName("img3")
        self.cam_1_3 = QtWidgets.QLabel(self.groupBox_3)
        self.cam_1_3.setEnabled(False)
        self.cam_1_3.setGeometry(QtCore.QRect(20, 120, 21, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.cam_1_3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wingdings 2")
        font.setPointSize(14)
        self.cam_1_3.setFont(font)
        self.cam_1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cam_1_3.setObjectName("cam_1_3")
        self.cam_2_3 = QtWidgets.QLabel(self.groupBox_3)
        self.cam_2_3.setEnabled(False)
        self.cam_2_3.setGeometry(QtCore.QRect(40, 120, 21, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.cam_2_3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wingdings 2")
        font.setPointSize(14)
        self.cam_2_3.setFont(font)
        self.cam_2_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cam_2_3.setObjectName("cam_2_3")
        self.cam_3_3 = QtWidgets.QLabel(self.groupBox_3)
        self.cam_3_3.setEnabled(False)
        self.cam_3_3.setGeometry(QtCore.QRect(60, 120, 21, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.cam_3_3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wingdings 2")
        font.setPointSize(14)
        self.cam_3_3.setFont(font)
        self.cam_3_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cam_3_3.setObjectName("cam_3_3")
        self.cam_4_3 = QtWidgets.QLabel(self.groupBox_3)
        self.cam_4_3.setEnabled(False)
        self.cam_4_3.setGeometry(QtCore.QRect(80, 120, 21, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.cam_4_3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wingdings 2")
        font.setPointSize(14)
        self.cam_4_3.setFont(font)
        self.cam_4_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cam_4_3.setObjectName("cam_4_3")
        self.cam_5_3 = QtWidgets.QLabel(self.groupBox_3)
        self.cam_5_3.setEnabled(False)
        self.cam_5_3.setGeometry(QtCore.QRect(100, 120, 21, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(68, 221, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 221, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.cam_5_3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wingdings 2")
        font.setPointSize(14)
        self.cam_5_3.setFont(font)
        self.cam_5_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cam_5_3.setObjectName("cam_5_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(180, 10, 141, 151))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.groupBox_2.setPalette(palette)
        self.groupBox_2.setObjectName("groupBox_2")
        self.nom_2 = QtWidgets.QLabel(self.groupBox_2)
        self.nom_2.setEnabled(True)
        self.nom_2.setGeometry(QtCore.QRect(16, 20, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.nom_2.setFont(font)
        self.nom_2.setAlignment(QtCore.Qt.AlignCenter)
        self.nom_2.setObjectName("nom_2")
        self.img2 = QtWidgets.QLabel(self.groupBox_2)
        self.img2.setEnabled(True)
        self.img2.setGeometry(QtCore.QRect(36, 42, 71, 71))
        self.img2.setText("")
        self.img2.setPixmap(QtGui.QPixmap("images/Cam2.png"))
        self.img2.setScaledContents(True)
        self.img2.setAlignment(QtCore.Qt.AlignCenter)
        self.img2.setObjectName("img2")
        self.cam_1_2 = QtWidgets.QLabel(self.groupBox_2)
        self.cam_1_2.setEnabled(False)
        self.cam_1_2.setGeometry(QtCore.QRect(20, 120, 21, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.cam_1_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wingdings 2")
        font.setPointSize(14)
        self.cam_1_2.setFont(font)
        self.cam_1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cam_1_2.setObjectName("cam_1_2")
        self.cam_2_2 = QtWidgets.QLabel(self.groupBox_2)
        self.cam_2_2.setEnabled(False)
        self.cam_2_2.setGeometry(QtCore.QRect(40, 120, 21, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.cam_2_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wingdings 2")
        font.setPointSize(14)
        self.cam_2_2.setFont(font)
        self.cam_2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cam_2_2.setObjectName("cam_2_2")
        self.cam_3_2 = QtWidgets.QLabel(self.groupBox_2)
        self.cam_3_2.setEnabled(False)
        self.cam_3_2.setGeometry(QtCore.QRect(60, 120, 21, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.cam_3_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wingdings 2")
        font.setPointSize(14)
        self.cam_3_2.setFont(font)
        self.cam_3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cam_3_2.setObjectName("cam_3_2")
        self.cam_4_2 = QtWidgets.QLabel(self.groupBox_2)
        self.cam_4_2.setEnabled(False)
        self.cam_4_2.setGeometry(QtCore.QRect(80, 120, 21, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.cam_4_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wingdings 2")
        font.setPointSize(14)
        self.cam_4_2.setFont(font)
        self.cam_4_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cam_4_2.setObjectName("cam_4_2")
        self.cam_5_2 = QtWidgets.QLabel(self.groupBox_2)
        self.cam_5_2.setEnabled(False)
        self.cam_5_2.setGeometry(QtCore.QRect(100, 120, 21, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(68, 221, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 221, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.cam_5_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wingdings 2")
        font.setPointSize(14)
        self.cam_5_2.setFont(font)
        self.cam_5_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cam_5_2.setObjectName("cam_5_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setEnabled(True)
        self.groupBox_4.setGeometry(QtCore.QRect(500, 10, 141, 151))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.groupBox_4.setPalette(palette)
        self.groupBox_4.setObjectName("groupBox_4")
        self.nom_4 = QtWidgets.QLabel(self.groupBox_4)
        self.nom_4.setEnabled(True)
        self.nom_4.setGeometry(QtCore.QRect(16, 20, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.nom_4.setFont(font)
        self.nom_4.setAlignment(QtCore.Qt.AlignCenter)
        self.nom_4.setObjectName("nom_4")
        self.img4 = QtWidgets.QLabel(self.groupBox_4)
        self.img4.setEnabled(True)
        self.img4.setGeometry(QtCore.QRect(36, 42, 71, 71))
        self.img4.setText("")
        self.img4.setPixmap(QtGui.QPixmap("images/Cam4.png"))
        self.img4.setScaledContents(True)
        self.img4.setAlignment(QtCore.Qt.AlignCenter)
        self.img4.setObjectName("img4")
        self.cam_1_4 = QtWidgets.QLabel(self.groupBox_4)
        self.cam_1_4.setEnabled(False)
        self.cam_1_4.setGeometry(QtCore.QRect(20, 120, 21, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.cam_1_4.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wingdings 2")
        font.setPointSize(14)
        self.cam_1_4.setFont(font)
        self.cam_1_4.setAlignment(QtCore.Qt.AlignCenter)
        self.cam_1_4.setObjectName("cam_1_4")
        self.cam_2_4 = QtWidgets.QLabel(self.groupBox_4)
        self.cam_2_4.setEnabled(False)
        self.cam_2_4.setGeometry(QtCore.QRect(40, 120, 21, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.cam_2_4.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wingdings 2")
        font.setPointSize(14)
        self.cam_2_4.setFont(font)
        self.cam_2_4.setAlignment(QtCore.Qt.AlignCenter)
        self.cam_2_4.setObjectName("cam_2_4")
        self.cam_3_4 = QtWidgets.QLabel(self.groupBox_4)
        self.cam_3_4.setEnabled(False)
        self.cam_3_4.setGeometry(QtCore.QRect(60, 120, 21, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.cam_3_4.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wingdings 2")
        font.setPointSize(14)
        self.cam_3_4.setFont(font)
        self.cam_3_4.setAlignment(QtCore.Qt.AlignCenter)
        self.cam_3_4.setObjectName("cam_3_4")
        self.cam_4_4 = QtWidgets.QLabel(self.groupBox_4)
        self.cam_4_4.setEnabled(False)
        self.cam_4_4.setGeometry(QtCore.QRect(80, 120, 21, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.cam_4_4.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wingdings 2")
        font.setPointSize(14)
        self.cam_4_4.setFont(font)
        self.cam_4_4.setAlignment(QtCore.Qt.AlignCenter)
        self.cam_4_4.setObjectName("cam_4_4")
        self.cam_5_4 = QtWidgets.QLabel(self.groupBox_4)
        self.cam_5_4.setEnabled(False)
        self.cam_5_4.setGeometry(QtCore.QRect(100, 120, 21, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(68, 221, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 221, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.cam_5_4.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wingdings 2")
        font.setPointSize(14)
        self.cam_5_4.setFont(font)
        self.cam_5_4.setAlignment(QtCore.Qt.AlignCenter)
        self.cam_5_4.setObjectName("cam_5_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 660, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Joueur 1"))
        self.nom_1.setText(_translate("MainWindow", "Nom 1"))
        self.cam_1_1.setText(_translate("MainWindow", "u"))
        self.cam_2_1.setText(_translate("MainWindow", "v"))
        self.cam_3_1.setText(_translate("MainWindow", "w"))
        self.cam_4_1.setText(_translate("MainWindow", "x"))
        self.cam_5_1.setText(_translate("MainWindow", "y"))
        self.lib_diffic.setText(_translate("MainWindow", "Question niveau 1 :"))
        self.lib_vraifaux.setText(_translate("MainWindow", ""))
        self.label_35.setText(_translate("MainWindow", "Votre réponse :"))
        self.bok.setText(_translate("MainWindow", "Ok"))
        self.bsuite.setText(_translate("MainWindow", "Suivant"))
        self.lib_question.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body align=\"center\" style=\" font-family:\'Calibri\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:5px; margin-right:5px; -qt-block-indent:0; text-indent:0px; font-size:14pt; color:#ffffff;\"><br /></p></body></html>"))
        self.lib_reponse.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_33.setText(_translate("MainWindow", "2020 - aude, céline, luigi, ludivine"))
        self.Titre.setText(_translate("MainWindow", "Data Pursuit"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Joueur 3"))
        self.nom_3.setText(_translate("MainWindow", "Nom 3"))
        self.cam_1_3.setText(_translate("MainWindow", "u"))
        self.cam_2_3.setText(_translate("MainWindow", "v"))
        self.cam_3_3.setText(_translate("MainWindow", "w"))
        self.cam_4_3.setText(_translate("MainWindow", "x"))
        self.cam_5_3.setText(_translate("MainWindow", "y"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Joueur 2"))
        self.nom_2.setText(_translate("MainWindow", "Nom 2"))
        self.cam_1_2.setText(_translate("MainWindow", "u"))
        self.cam_2_2.setText(_translate("MainWindow", "v"))
        self.cam_3_2.setText(_translate("MainWindow", "w"))
        self.cam_4_2.setText(_translate("MainWindow", "x"))
        self.cam_5_2.setText(_translate("MainWindow", "y"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Joueur 4"))
        self.nom_4.setText(_translate("MainWindow", "Nom 4"))
        self.cam_1_4.setText(_translate("MainWindow", "u"))
        self.cam_2_4.setText(_translate("MainWindow", "v"))
        self.cam_3_4.setText(_translate("MainWindow", "w"))
        self.cam_4_4.setText(_translate("MainWindow", "x"))
        self.cam_5_4.setText(_translate("MainWindow", "y"))


    #------------------------CODER ICI ----------------------------------------------# 
        self.bok.clicked.connect(self.traiter_reponse) # action lorsque on appuie sur le bouton ok (appeler fonction traiter_reponse)
        self.bsuite.clicked.connect(self.suite_du_tour) # action lorsque l'on appuie sur le bouton suivant (la fonction suite_du_tour)
        # --------------init-----------------#
        self.groupBox_2.hide()
        self.groupBox_3.hide()
        self.groupBox_4.hide()

        self.data = Bdd()

        liste_joueurs = self.recup_noms()

        param_init = self.initjoueurs(liste_joueurs)
        self.dico_joueurs = param_init[0]
        self.liste_labels = param_init[1]

        self.stockage = []
        self.id_en_jeu = 1

        # --------------debut du jeu-----------------#
        self.tour = 1
        self.jeu()
        

            #--------------gameplay--------------#
    #----------------------------------------------------------------------#
    def jeu(self):

        param_question = self.poser_question(self.dico_joueurs, self.liste_labels, self.stockage, self.id_en_jeu)
        self.id_question = param_question[0][0]
        self.theme = param_question[2]
        self.difficulte = param_question[0][2]
        
        self.stockage = param_question[1]
        reponse_donnee = self.traiter_reponse() 
        reponse_origine= self.data.obtenir_reponse_id(self.id_question)

        return

    def recup_noms(self):
        return ["Lewis", "Fernando", "Romain"]

    def initjoueurs(self, arg):
        self.dico_joueurs = {}
        self.liste_labels =[]
        joueur1 = Joueur(arg[0])
        self.dico_joueurs[1] = joueur1
        self.nom_1.setText(joueur1.nom)
        self.liste_labels.append(self.nom_1)
        if len(arg)>1:
            joueur2 = Joueur(arg[1])
            self.dico_joueurs[2] = joueur2
            self.nom_2.setText(joueur2.nom)
            self.liste_labels.append(self.nom_2)
            self.groupBox_2.show()
        if len(arg)>2:
            joueur3 = Joueur(arg[2])
            self.dico_joueurs[3] = joueur3
            self.nom_3.setText(joueur3.nom)
            self.liste_labels.append(self.nom_3)
            self.groupBox_3.show()
        if len(arg)>3:
            joueur4 = Joueur(arg[3])
            self.dico_joueurs[4] = joueur4
            self.nom_4.setText(joueur4.nom)
            self.liste_labels.append(self.nom_4)
            self.groupBox_4.show()
        print(self.dico_joueurs)
        print(self.liste_labels)

        return self.dico_joueurs, self.liste_labels


    def j_suivant(self):
        if self.id_en_jeu == (len(self.dico_joueurs)):            
            self.id_en_jeu = 1
        else :
            self.id_en_jeu +=1
        
        return


    def poser_question(self, dico_joueurs, liste_labels, stockage, id_en_jeu) :
        # initialisation

        self.stockage = stockage
        
        self.dico_joueurs = dico_joueurs
        self.liste_labels = liste_labels

        statut = True
  #      while statut == True:
        a = self.question_aleatoire(self.stockage) #    return aleatoire_question[0], stock_id_question, theme_choisi
        id_question = a[0][0]
        libelle = a[0][1]
        self.difficulte = a[0][2]
        self.stockage = a[1]
        theme = a[2]
        # donner difficulté 
        self.lib_diffic.setText("Question niveau " + str(self.difficulte))
        self.label_35.setText("Tour: " + str(self.dico_joueurs[self.id_en_jeu]))
        self.lib_question.setText(libelle)

        return a

    def traiter_reponse(self):
        if self.champ.text():

            reponse = self.champ.text()
            self.champ.clear()
            statut, self.dico_joueurs[self.id_en_jeu]= traitement_reponse(reponse, self.id_question, self.dico_joueurs[self.id_en_jeu], self.theme, 3, self.stockage )
            ###########################################remettre la difficulte !!!! ###########################################################""
            reponse_origine= Bdd.obtenir_reponse_id(self.id_question) #query qui récupère la bonne réponse 
            reponse_origine = reponse_origine[0][0] 

            if statut == False:
                self.lib_reponse.setText("mauvaise réponse, dommage ! " + str(reponse_origine))
                self.j_suivant()
            else:
                self.lib_reponse.setText("bonne réponse ! ")
        
        return self.dico_joueurs[self.id_en_jeu]


    def suite_du_tour(self):

        self.lib_reponse.clear()
        self.tour = self.tour + 1 #rajoute un tour
        self.jeu()
        return self.tour


    def question_aleatoire(self, stockage):
        self.data = Bdd()

        aleatoire_question = []
        self.stockage = stockage
        themes = self.data.lister_themes()

        themes_au_choix = random.sample(themes,2)
        
        theme_choisi = themes_au_choix[0][0]

        liste_question = self.data.lister_questions_theme(theme_choisi)

        aleatoire_question = random.sample(liste_question,1)
        while aleatoire_question[0][0] in self.stockage : # comparer avec le stock pour voir si la question a 
            aleatoire_question = random.sample(liste_question,1) # déjà été posée
        id_question = aleatoire_question[0][0]
        self.stockage.append(id_question)
        if len(liste_question) == 0: #rajout de toutes les questions supprimées si liste_question est vide !!!!! A REVOIR
            self.stock_id_question = []

        return aleatoire_question[0], self.stockage, theme_choisi



      

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()


    sys.exit(app.exec_())
